## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://db:5433/postgres
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    database: postgresql
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: true;
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
#     dialect: org.hibernate.dialect.PostgreSQL95Dialect

#  jackson:
#    default-property-inclusion: non_null
#  redis:
#    host: localhost
#    port: 6379
#  freemarker:
#      cache: false




  queries:
    users-query: select email, password, active from users where email=?
    roles-query: select email, role from users where email=?
server:
  servlet:
    contextPath: /api

jwtSecret: com.dmaksimn
jwtExpiration: 86400
